# fly.toml file generated for fso-cicd on 2022-11-16T18:50:49+01:00

app = "fso-cicd"
kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
  release_command = "npm run build"

[env]
  PORT = "5100"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[processes]
  app = "node app.js"

[[services]]
  internal_port = 5100
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

 [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]

  [[services.script_checks]]
    interval = 10000
    timeout = 1000
    command = "./health_check.sh"
    restart_limit = 0
