name: Health Check

on:
  schedule:
    - cron: '0 20 * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://fso-cicd.fly.dev/health
          max-attempts: 3
          retry-delay: 5s
